### ISSUE TITLE
Question: Not using 5volt power from the gateway possible?

### ISSUE THREAD

**Issue by mrWheel** [jpraus/arduino-opentherm#12]
Hi,

My ATAG boiler has a 24Volt output, but can only deliver 100mA which is not enough for an ESP8266 to work properly. 

So my question is:
If I connect the Opentherm Gateway to the 24v from the boiler and don't connect the 5v out of the gateway to anything but power the ESP8266 by an external 3v3 power supply, will that work?
I will of course connect GND from the gateway to the GND of the ESP8266!

**Comment by jpraus** [comment]
Theoretically, 100mA on 24V should be enough for ESP to run, because when the voltage regulator steps down the voltage from 24V to 5V it increases the current. Ideally, it would be 480mA but that is not real due to losses. ESP should be able to run with 250mA so you should be perfectly ok using the power source of your boiler. If that does not work, you can always use a 3.3V external power source, but make sure to use it as a logic voltage on the shield (ground connected together of course).
